### ISSUE TITLE
Clone button for Form questions?

### ISSUE THREAD

**Issue by JohnSmith-LT** [WebPA/Source#11]
Hi,

Seems to me that there is opportunity to enhance the Form creation process. Was creating a form that had several questions and all were using a Likert scale with similar options. I realised a clone button on questions would be useful so I added it - is this of interest to people or am I missing something?

Looks like this just now and simple code change to add:

![image](https://cloud.githubusercontent.com/assets/3907362/26357188/75819d40-3fc6-11e7-9c9a-df001223d848.png)

I won't add though yet until it's confirmed that this is desirable...

John

**Comment by neilgordon** [comment]
A clone button sounds useful – something that eases the users jobs!

**Comment by JohnSmith-LT** [comment]
Not happy with icon but quickest free one I could locate...

I can't add a # **"Please Test"** flag so just adding message here for now...
