### ISSUE TITLE
Default branch

### ISSUE THREAD

**Issue by JohnSmith-LT** [WebPA/Source#14]
Not sure who has full admin of this repo but can we have the default branch set to 'develop' instead of 'master'

Not sure if it makes a difference to anyone but since mostly Github will be used for development then it might be useful if the develop branch is the default that you get..

For example with Xerte when you enter the repo or click on the 'code' tab it takes you to develop

Click here: https://github.com/thexerteproject/xerteonlinetoolkits

But with this repo it takes you to the master branch...

Click here: https://github.com/WebPA/Source

**Comment by mcrauwel** [comment]
+1 you'll need an admin to change this for you...

**Comment by bulphan** [comment]
Hi all,

I've updated as requested.

Regards,

Rich

****************************************************************
Richard Goodman
IT Services
Loughborough University

**Comment by JohnSmith-LT** [comment]
Thanks Rich!
